@startuml

enum tipoSuperficie{
    CESPED
    TIERRA_BATIDA
    PISTA_DURA
}

class Equipo{

}

class Jugador{
    - nombre : String
    - posicionRanking : Int
    - fechaNacimiento : Date
    - nacionalidad : String
    - calcularPartidosGanados() :


}

class Pareja{



}

class Sede{

}

class Eliminatoria{
    - setJugadoresParticipantes : Jugador
    - 
}

class Partido{
    - numero : Int

}

class PartidoIndividual{
    - ganador : Jugador
    - marcador : String

}

class PartidoDobles{
    - parejaGanadora : Pareja                                                                                                                                                                                                                

}
class Superficie{
    
}

class Resultado{

}

Eliminatoria "1" -- "0..*" Partido : contiene

Pareja "1" -- "2" Jugador : está formada

Partido <|-- PartidoIndividual

Partido <|-- PartidoDobles


PartidoDobles "1" -- "1" Pareja : parejaLocal

PartidoDobles "1" -- "1" Pareja : parejaVisitante

note right of PartidoIndividual
El ganador tiene que ser uno de los jugadores que participan en el partido.
end note
note right of Partido
Dependiendo de PARTIDO.numero pueden ser : Partido 1 y 2: individuales. Partido 3: dobles. Partido 4 y 5: individuales.
end note
@enduml