@startuml

class Cliente{
    - nombre: String
    - direccionEnvio : String
    - telefono : Int
    - correo : String
}

class Producto{ 
    - codigo : Int
    - stock : Int
    - nombre : String
    - descripcion : String
    - pvp : Double
}

class Cuenta{
    - numero : Int
    - saldo : Double
    + recargarSaldo(saldo : Double) : void
    + comprar(saldo : Double)
}

class TarjetaCredito{
    - numero : Int
    - saldo : Double
    - fechaVencimiento : Date
}

class LineaPedido{
    - cantidad : Int
    - precioProducto : Double
}

class Pedido{
    - estado : estadoPedido
    - costo : Int 
    - numero : Int

}

class PedidoSimple{

}

class PedidoCompuesto{

}

enum estadoPedido{
    PENDIENTE
    COBRADO
    DISTRIBUCION
    CONFIRMADO
}

class ProcesadorCobros <<singleton>>{
    realizarRevision(estado : estadoPedido) : void 
}

Cliente "1" *-- "0..*" Cuenta : propietario

Cuenta "1" -- "0..*" Pedido : realiza {restriccion : La cuenta sólo puede realizar un pedido si CUENTA.saldo > PEDIDO.costo}

Cliente "1" -- "0..*" Pedido : pide {restriccion : Un cliente solo puede pedir un pedido si la cuenta con la que se paga el pedido es de su propiedad.}

Cuenta "1" -- "1" TarjetaCredito : usa

Pedido <|-- PedidoSimple 
Pedido <|-- PedidoCompuesto

PedidoSimple "0..*" -- "1" Cuenta : paga

PedidoCompuesto "0..1" *-- "0..*" Pedido : contiene

Pedido "1" -- "0..*" LineaPedido : posee

LineaPedido "1" -- "1" Producto : pertenece {restricción: Sólo se puede pedir un producto si PRODUCTO.stock > 0}





note right of PedidoSimple
{restricción : Máximo 20 productos por Pedido}
end note

@enduml