@startuml

class Autor{
- nombre: String
- apellido : String
- nacionalidad : String
- fechaNacimiento : Date
+ escribir() : void
+ getNombreCompleto() : String {derived}

}

class Libro{
- titulo: String
- isbn: Int
- numeroPaginas : Int
- precio : Double
+ leer() : void
+ getTitulo() : String
+ getPrecio() : Double

}


Autor "1" --> "0..*" Libro : escribe 

note right of Autor
getNombreCompleto() devuelve
nombre + " " + apellido
end note

@enduml

